version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=discord
      - POSTGRES_DB=discord_dev
    ports:
      - 5432:5432